const courses =
  [
    {
      id: "cs01",
      courseName: "cse",
      items: [
        {
          itemid: "CSEI01",
          noofcards: 7,
          domain: "Programing Language",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Programin in C",
              desc: "This is a card related to programing language",
              author: "Harry",
              imgurl: "cse_img/c.jfif",
              playlistId: "PLu0W_9lII9aiXlHcLx-mDH1Qul38wD3aR",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Object Oriented Programing with C++",
              desc: "This is a card related to programing language",
              author: "Harry",
              imgurl: "cse_img/cpp.jfif",
              playlistId: "PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Object Oriented Programing with Java ",
              desc: "This is a card related to programing language",
              author: "Harry",
              imgurl: "cse_img/java.png",
              playlistId: "PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q",
            },
            {
              cardId: "CSEC04",
              cardTitle: "Programing in Python",
              desc: "This is a card related to programing language",
              author: "Harry",
              imgurl: "cse_img/python.jfif",
              playlistId: "PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME",
            },
          ],
        },
        {
          itemid: "CSEI02",
          noofcards: 3,
          domain: "Database Management System",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Database Management System",
              desc: "This is a card related to database management",
              author: "Varun Singla",
              imgurl: "cse_img/dbms.png",
              playlistId: "PLxCzCOWd7aiFAN6I8CuViBuCdJgiOkT2Y",
            },
            {
              cardId: "CSEC02",
              cardTitle: "SQL",
              desc: "This is a card related to database management",
              author: "Manish Sharma",
              imgurl: "cse_img/sql.png",
              playlistId: "PLL_LQvNX4xKwbz1aJe0RofbT9YeJH9huQ",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Pl/Sql",
              desc: "This is a card related to database management",
              author: "Manish Sharma",
              imgurl: "cse_img/plsql.png",
              playlistId: "PLL_LQvNX4xKyiExzq9GKwORoH6nvaRnOQ",
            },
          ],
        },
        {
          itemid: "CSEI03",
          noofcards: 1,
          domain: "Data Structure And Algorith",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Data Structure And Algorithm,",
              desc: "This is a card related to data structure and algorithm",
              author: "Abdul Bari",
              imgurl: "cse_img/dsa.jfif",
              playlistId: "PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O",
            },
          ],
        },
        {
          itemid: "CSEI04",
          noofcards: 2,
          domain: "Development",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Web Development",
              desc: "This is a card related to development",
              author: "Harry",
              imgurl: "cse_img/web.jfif",
              playlistId: "PLu0W_9lII9agiCUZYRsvtGTXdxkzPyItg",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Android Development with Java",
              desc: "This is a card related to development",
              author: "Harry",
              imgurl: "cse_img/android.jfif",
              playlistId: "PLu0W_9lII9aiL0kysYlfSOUgY5rNlOhUd",
            },
          ],
        },
        {
          itemid: "CSEI05",
          noofcards: 3,
          domain: "Artificial Intelligence",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Fundamentals of AI",
              desc: "This is a card related to artificial intelligence",
              author: "Varun Singla",
              imgurl: "cse_img/ai.jfif",
              playlistId: "PLxCzCOWd7aiHGhOHV-nwb0HR5US5GFKFI",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Machine Learning",
              desc: "This is a card related to artificial intelligence",
              author: "Harry",
              imgurl: "cse_img/ml.jfif",
              playlistId: "PLu0W_9lII9ai6fAMHp-acBmJONT7Y4BSG",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Deep Learning",
              desc: "This is a card related to artificial intelligence",
              author: "Prof. Mitesh Khapra",
              imgurl: "cse_img/deep.jfif",
              playlistId: "PLyqSpQzTE6M9gCgajvQbc68Hk_JKGBAYT",
            },
            {
              cardId: "CSEC04",
              cardTitle: "Reinforcement Learning",
              desc: "This is a card related to artificial intelligence",
              author: "Prof. Balaraman Ravindran",
              imgurl: "cse_img/rl.jfif",
              playlistId: "PLEAYkSg4uSQ0Hkv_1LHlJtC_wqwVu6RQX",
            },
          ],
        },
        {
          itemid: "CSEI06",
          noofcards: 3,
          domain: "System Design",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Compiler Design",
              desc: "This is a card related to system design",
              author: "Varun Singla",
              imgurl: "cse_img/cd.jfif",
              playlistId: "PLxCzCOWd7aiEKtKSIHYusizkESC42diyc",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Operating System",
              desc: "This is a card related to system design",
              author: "Varun Singla",
              imgurl: "cse_img/os.jfif",
              playlistId: "PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Computer Networks",
              desc: "This is a card related to system design",
              author: "Varun Singla",
              imgurl: "cse_img/cn.jfif",
              playlistId: "PLxCzCOWd7aiGFBD2-2joCpWOLUrDLvVV_",
            },
          ],
        },
        {
          itemid: "CSEI07",
          noofcards: 2,
          domain: "Data Science",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Python for Data Science ",
              desc: "This is a card related to data science",
              author: "NPTEL IITM",
              imgurl: "cse_img/ds.jfif",
              playlistId: "PLyqSpQzTE6M_fFg1zZmeGIkenMDgXKGYi",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Data Science for Engineers",
              desc: "This is a card related to data science",
              author: "NPTEL IITM",
              imgurl: "cse_img/dse.jfif",
              playlistId: "PLyqSpQzTE6M-Rf2y3MT5aZ1UpTF1UQBK0",
            },
          ],
        },
        {
          itemid: "CSEI08",
          noofcards: 4,
          domain: "Other Courses",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Computer Architecture and Organization",
              desc: "This is a card related to other courses",
              author: "Varun Singla",
              imgurl: "cse_img/coa.png",
              playlistId: "PLxCzCOWd7aiHMonh3G6QNKq53C6oNXGrX",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Theory of Computation",
              desc: "This is a card related to other courses",
              author: "Varun Singla",
              imgurl: "cse_img/toc.jfif",
              playlistId: "PLxCzCOWd7aiFM9Lj5G9G_76adtyb4ef7i",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Software Engineering",
              desc: "This is a card related to other courses",
              author: "Varun Singla",
              imgurl: "cse_img/se.jfif",
              playlistId: "PLxCzCOWd7aiEed7SKZBnC6ypFDWYLRvB2",
            },
            {
              cardId: "CSEC04",
              cardTitle: "Microprocessor Architecture",
              desc: "This is a card related to other courses",
              author: "Tutorials Point",
              imgurl: "cse_img/mpa.jfif",
              playlistId: "PLWPirh4EWFpFDi8bggPYOiMLlD1D_bBPM",
            },
            {
              cardId: "CSEC05",
              cardTitle: "Computer Graphics",
              desc: "This is a card related to other courses",
              author: "Deepak Garg",
              imgurl: "cse_img/cg.png",
              playlistId: "PLL8qj6F8dGlScni_9ZmeOMoRodrwzhvTq",
            },
            {
              cardId: "CSEC06",
              cardTitle: "Digital Logic And Design",
              desc: "This is a card related to other courses",
              author: "Varun Singla",
              imgurl: "cse_img/dld.jfif",
              playlistId: "PLxCzCOWd7aiGmXg4NoX6R31AsC5LeCPHe",
            },
          ],
        },
      ],
    },


    {
      id: "me01",
      courseName: "mechanical",
      items: [
        {
          itemid: "MEI01",
          noofcards: 6,
          domain: "Robotics",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "Robotics",
              desc: "This is a card related to robotics",
              author: "Prof. D K Pratihar",
              imgurl: "me_img/r6.jfif",
              playlistId: "PLbRMhDVUMngcdUbBySzyzcPiFTYWr4rV_",
            },
            {
              cardId: "MEC02",
              cardTitle: "Introduction to Robotics",
              desc: "This is a card related to robotics",
              author: "NPTEL IITM",
              imgurl: "me_img/r5.jfif",
              playlistId: "PLyqSpQzTE6M_XM9cvjLLO_Azt1FkgPhpH",
            },
            {
              cardId: "MEC03",
              cardTitle: "Robotics and Control: Theory and Practice",
              desc: "This is a card related to robotics",
              author: "IIT ROORKEE",
              imgurl: "me_img/r4.jfif",
              playlistId: "PLLy_2iUCG87AjAXKbNMiKJZ2T9vvGpMB0",
            },
            {
              cardId: "MEC04",
              cardTitle: "Mechanics and Control of Robotic Manipulators",
              desc: "This is a card related to robotics",
              author: "NPTEL IITM",
              imgurl: "me_img/r3.jfif",
              playlistId: "PLyqSpQzTE6M-tWPjnJjFo9sHGWxgCnGrh",
            },
            {
              cardId: "MEC05",
              cardTitle: "Robotics: Basics and Selected Advanced Concepts",
              desc: "This is a card related to robotics",
              author: "IISC Banglore",
              imgurl: "me_img/r2.jfif",
              playlistId: "PLgMDNELGJ1CZT9pdEEkDylXFPLdcqxn0t",
            },
            {
              cardId: "MEC06",
              cardTitle: "Industrial Robotics and Automation Course",
              desc: "This is a card related to robotics",
              author: "Arun Dayal Udai",
              imgurl: "me_img/r1.jfif",
              playlistId: "PLXDsvE7qtfNdt9oYEhJ_LMXDUGu6bH-L6",
            },
          ],
        },
        {
          itemid: "MEI02",
          noofcards: 7,
          domain: "Thermodynamics",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "Introduction to Thermodynamics",
              desc: "This is a card related to thermodynamics",
              author: "NPTEL IITM",
              imgurl: "me_img/th1.jfif",
              playlistId: "PLyqSpQzTE6M_QOKxVxZ5nQ48gOkzg7zWP",
            },
            {
              cardId: "MEC02",
              cardTitle: "MATLAB Programming for Numerical Computation NPTEL",
              desc: "This is a card related to thermodynamics",
              author: "Prof. Niket",
              imgurl: "me_img/th2.jfif",
              playlistId: "PLRWKj4sFG7-6_Xr9yqg6SMr_F80KdFVhN",
            },
            {
              cardId: "MEC03",
              cardTitle: "Thermodynamics: classical to statistical",
              desc: "This is a card related to thermodynamics",
              author: "NPTEL IIT Guwahati",
              imgurl: "me_img/th3.jfif",
              playlistId: "PLwdnzlV3ogoX-WIPb5DnmmmUOVAgI5wrq",
            },
            {
              cardId: "MEC04",
              cardTitle: "Advanced Thermodynamics and Combustion",
              desc: "This is a card related to thermodynamics",
              author: "Prof. Niranjan Sahoo",
              imgurl: "me_img/th4.jfif",
              playlistId: "PLwdnzlV3ogoUcPrKLKz1_j0s89VzvZfnx",
            },
            {
              cardId: "MEC05",
              cardTitle: "Chemical Engineering Thermodynamics",
              desc: "This is a card related to thermodynamics",
              author: "Prof. Shashidhar Gumma",
              imgurl: "me_img/th5.jfif",
              playlistId: "PLwdnzlV3ogoVnCnIfjDHng_8biZSUEYtK",
            },
            {
              cardId: "MEC06",
              cardTitle: "Thermodynamics - GATE",
              desc: "This is a card related to thermodynamics",
              author: "GATE Academy Plus",
              imgurl: "me_img/th6.jfif",
              playlistId: "PL9RcWoqXmzaK6AHCCyL_J6gqc02RN-w-D",
            },
            {
              cardId: "MEC07",
              cardTitle: "Engineering Thermodynamics",
              desc: "This is a card related to thermodynamics",
              author: "EveryEng - Mechanical",
              imgurl: "me_img/th7.png",
              playlistId: "PLDDfbf7FIeqsPqMnCiU6dvkb6TbG21ucz",
            },
          ],
        },
        {
          itemid: "MEI03",
          noofcards: 4,
          domain: "Propulsion",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "IC Engines and Gas Turbines",
              desc: "This is a card related to propulsion",
              author: "NPTEL IITM",
              imgurl: "me_img/pp1.jfif",
              playlistId: "PLwdnzlV3ogoXHbVNKWL1BYOo_8PpyNtnC",
            },
            {
              cardId: "MEC02",
              cardTitle: "Fundamentals of Automotive Systems",
              desc: "This is a card related to propulsion",
              author: "NPTEL IITM",
              imgurl: "me_img/pp2.jfif",
              playlistId: "PLyqSpQzTE6M9G2SNxKfsVEjcM9MlJau4F",
            },
            {
              cardId: "MEC03",
              cardTitle: "Aircraft Propulsion",
              desc: "This is a card related to propulsion",
              author: "Prof. Vinayak Kulkarni",
              imgurl: "me_img/pp3.jfif",
              playlistId: "PLwdnzlV3ogoWEYkr5o3OD4cv5v7ba10Lm",
            },
            {
              cardId: "MEC04",
              cardTitle: "Introduction to Rocket Propulsion",
              desc: "This is a card related to propulsion",
              author: "Prof. Dr D.P. Mishra",
              imgurl: "me_img/pp4.jfif",
              playlistId: "PLFW6lRTa1g82gOQCc1aR4r7uyCbdmpL0D",
            },
          ],
        },
        {
          itemid: "MEI04",
          noofcards: 6,
          domain: "Mechanics",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "Engineering Mechanics",
              desc: "This is a card related to mechanics",
              author: "NPTEL IITM",
              imgurl: "me_img/m2.jfif",
              playlistId: "PLyqSpQzTE6M_MEUdn1izTMB2yZgP1NLfs",
            },
            {
              cardId: "MEC02",
              cardTitle: "Theoretical Mechanics",
              desc: "This is a card related to mechanics",
              author: "NPTEL IIT Guwahati",
              imgurl: "me_img/m3.jfif",
              playlistId: "PLwdnzlV3ogoXUbQmP-T2gPhYXeEcxP6U8",
            },
            {
              cardId: "MEC03",
              cardTitle: "Classical Mechanics",
              desc: "This is a card related to mechanics",
              author: "IIT Kharagpur",
              imgurl: "me_img/m4.jfif",
              playlistId: "PLdOM9VfSZfHNPDJCUthjWHBeAgyn3IuzM",
            },
            {
              cardId: "MEC04",
              cardTitle: "",
              desc: "This is a card related to mechanics",
              author: "",
              imgurl: "me_img/m5.png",
              playlistId: "",
            },
            {
              cardId: "MEC05",
              cardTitle: "Introduction to Classical Mechanics",
              desc: "This is a card related to mechanics",
              author: "NPTEL IITM",
              imgurl: "me_img/m6.jfif",
              playlistId: "PLyqSpQzTE6M_d9f-9fKxUQYR1qI5YEnSz",
            },
            {
              cardId: "MEC06",
              cardTitle: "Engineering Mechanics ",
              desc: "This is a card related to mechanics",
              author: "Unacademy",
              imgurl: "me_img/m7.jfif",
              playlistId: "PLiSPNzs4fD9tyI_gNHcQkvtvzLvB3aE05",
            },
          ],
        },
        {
          itemid: "MEI05",
          noofcards: 6,
          domain: "Dynamics and Vibration",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "Mechanical Vibration",
              desc: "This is a card related to dynamics and vinration",
              author: "Unacademy",
              imgurl: "me_img/dv3.jfif",
              playlistId: "PLiSPNzs4fD9spvBAr_fpt5SIe-Eg1YoN9",
            },
            {
              cardId: "MEC02",
              cardTitle: "Vibration and Structural Dynamics",
              desc: "This is a card related to dynamics and vinration",
              author: "Prof. Mira Mitra",
              imgurl: "me_img/dv4.jfif",
              playlistId: "PLbRMhDVUMngdM3vvYapHCEPTiEvoATCHS",
            },
            {
              cardId: "MEC03",
              cardTitle: "Introduction to Mechanical Vibration",
              desc: "This is a card related to dynamics and vinration",
              author: "Dr. Anil Kumar",
              imgurl: "me_img/dv5.jfif",
              playlistId: "PLSGws_74K01_pG3R7rgtDtrDZBjcTgPdR",
            },
            {
              cardId: "MEC04",
              cardTitle: "Dynamics of Machinery",
              desc: "This is a card related to dynamics and vinration",
              author: "Mechanical & Automobile",
              imgurl: "me_img/dv6.jfif",
              playlistId: "PLQmc-I2-FO2HKvASHKTX3_T6s0PD6DtWj",
            },
            {
              cardId: "MEC05",
              cardTitle: "DOM(Vibration)",
              desc: "This is a card related to dynamics and vinration",
              author: "Education Lessons",
              imgurl: "me_img/dv1.jfif",
              playlistId: "PLwpA_XrwdvgYT6cqLRYVOgy8hS1h0UnmI",
            },
            {
              cardId: "MEC06",
              cardTitle: "Vibration",
              desc: "This is a card related to dynamics and vinration",
              author: "Unacademy",
              imgurl: "me_img/dv2.jfif",
              playlistId: "PLiSPNzs4fD9s0sCnTRd6M6gX86BHCCJOH",
            },
          ],
        },
      ],
    }


  ];
module.exports = courses;