const courses =
  [
    {
      id: "cs01",
      courseName: "cse",
      items: [
        {
          itemid: "CSEI01",
          noofcards: 6,
          domain: "Programing Data Structure And Algorithm",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Programin in C",
              desc: "This is a card related to programing language",
              author: "Harry",
              imgurl: "cse_img/c.jfif",
              playlistId: "PLu0W_9lII9aiXlHcLx-mDH1Qul38wD3aR",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Object Oriented Programing with C++",
              desc: "This is a card related to programing language",
              author: "Harry",
              imgurl: "cse_img/cpp.jfif",
              playlistId: "PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Object Oriented Programing with Java ",
              desc: "This is a card related to programing language",
              author: "Harry",
              imgurl: "cse_img/java.png",
              playlistId: "PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q",
            },
            {
              cardId: "CSEC04",
              cardTitle: "Programing in Python",
              desc: "This is a card related to programing language",
              author: "Harry",
              imgurl: "cse_img/python.jfif",
              playlistId: "PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME",
            },
            {
              cardId: "CSEC05",
              cardTitle: "Data Structure And Algorithm",
              desc: "This is a card related to data structure and algorithm",
              author: "Abdul Bari",
              imgurl: "cse_img/dsa.jfif",
              playlistId: "PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O",
            },
            {
              cardId: "CSEC06",
              cardTitle: "C++ Programing",
              desc: "This is a card related to programing",
              author: "Neso Academy",
              imgurl: "cse_img/csx1.webp",
              playlistId: "PLBlnK6fEyqRh6isJ01MBnbNpV3ZsktSyS",
            },
          ],
        },
        {
          itemid: "CSEI02",
          noofcards: 6,
          domain: "Database Management System",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Database Management System",
              desc: "This is a card related to database management",
              author: "Varun Singla",
              imgurl: "cse_img/dbms.png",
              playlistId: "PLxCzCOWd7aiFAN6I8CuViBuCdJgiOkT2Y",
            },
            {
              cardId: "CSEC02",
              cardTitle: "SQL",
              desc: "This is a card related to database management",
              author: "Manish Sharma",
              imgurl: "cse_img/sql.png",
              playlistId: "PLL_LQvNX4xKwbz1aJe0RofbT9YeJH9huQ",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Pl/Sql",
              desc: "This is a card related to database management",
              author: "Manish Sharma",
              imgurl: "cse_img/plsql.png",
              playlistId: "PLL_LQvNX4xKyiExzq9GKwORoH6nvaRnOQ",
            },
            {
              cardId: "CSEC04",
              cardTitle: "Sql Server",
              desc: "This is a card related to database management",
              author: "kudvenkat",
              imgurl: "cse_img/csx2.webp",
              playlistId: "PL08903FB7ACA1C2FB",
            },
            {
              cardId: "CSEC05",
              cardTitle: "PostgreSQL",
              desc: "This is a card related to database management",
              author: "Programing Guru",
              imgurl: "cse_img/csx3.webp",
              playlistId: "PLk1kxccoEnNEtwGZW-3KAcAlhI_Guwh8x",
            },
            {
              cardId: "CSEC06",
              cardTitle: "My Sql",
              desc: "This is a card related to database management",
              author: "Programing Knowledge",
              imgurl: "cse_img/csx4.png",
              playlistId: "PLS1QulWo1RIY4auvfxAHS9m_fZJ2wxSse",
            },
          ],
        },
        {
          itemid: "CSEI04",
          noofcards: 6,
          domain: "Development",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Web Development",
              desc: "This is a card related to development",
              author: "Harry",
              imgurl: "cse_img/web.jfif",
              playlistId: "PLu0W_9lII9agiCUZYRsvtGTXdxkzPyItg",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Android Development with Java",
              desc: "This is a card related to development",
              author: "Harry",
              imgurl: "cse_img/android.jfif",
              playlistId: "PLu0W_9lII9aiL0kysYlfSOUgY5rNlOhUd",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Bootstrap",
              desc: "This is a card related to development",
              author: "kudvenkat",
              imgurl: "cse_img/csx5.jfif",
              playlistId: "PL6n9fhu94yhXd4xnk-j5FGhHjUv1LsF0V",
            },
            {
              cardId: "CSEC04",
              cardTitle: "JavaScript",
              desc: "This is a card related to development",
              author: "Harry",
              imgurl: "cse_img/js.jfif",
              playlistId: "PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR",
            },
            {
              cardId: "CSEC05",
              cardTitle: "CSS",
              desc: "This is a card related to development",
              author: "Tech GUn",
              imgurl: "cse_img/css.png",
              playlistId: "PLjpp5kBQLNTSFXXi-bfskBXG178FGkftU",
            },
            {
              cardId: "CSEC06",
              cardTitle: "Web Security",
              desc: "This is a card related to development",
              author: "Simplilearn",
              imgurl: "cse_img/sec.png",
              playlistId: "PLEiEAq2VkUUJfPOj5nRounXvf3n17PCft",
            },
          ],
        },
        {
          itemid: "CSEI05",
          noofcards: 6,
          domain: "Artificial Intelligence",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Fundamentals of AI",
              desc: "This is a card related to artificial intelligence",
              author: "Varun Singla",
              imgurl: "cse_img/ai.jfif",
              playlistId: "PLxCzCOWd7aiHGhOHV-nwb0HR5US5GFKFI",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Machine Learning",
              desc: "This is a card related to artificial intelligence",
              author: "Harry",
              imgurl: "cse_img/ml.jfif",
              playlistId: "PLu0W_9lII9ai6fAMHp-acBmJONT7Y4BSG",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Deep Learning",
              desc: "This is a card related to artificial intelligence",
              author: "Prof. Mitesh Khapra",
              imgurl: "cse_img/deep.jfif",
              playlistId: "PLyqSpQzTE6M9gCgajvQbc68Hk_JKGBAYT",
            },
            {
              cardId: "CSEC04",
              cardTitle: "Reinforcement Learning",
              desc: "This is a card related to artificial intelligence",
              author: "Prof. Balaraman Ravindran",
              imgurl: "cse_img/rl.jfif",
              playlistId: "PLEAYkSg4uSQ0Hkv_1LHlJtC_wqwVu6RQX",
            },
            {
              cardId: "CSEC05",
              cardTitle: "Artificial Intelligence",
              desc: "This is a card related to artificial intelligence",
              author: "Easy Engineering Classes",
              imgurl: "cse_img/csx6.jfif",
              playlistId: "PLV8vIYTIdSnYsdt0Dh9KkD9WFEi7nVgbe",
            },
            {
              cardId: "CSEC06",
              cardTitle: "Applied Accelerated Artificial Intelligence",
              desc: "This is a card related to artificial intelligence",
              author: "NPTEL IITM",
              imgurl: "cse_img/csx7.jfif",
              playlistId: "PLyqSpQzTE6M9LibNqhhCYLDvfVGhcRDN4",
            },
          ],
        },
        {
          itemid: "CSEI06",
          noofcards: 3,
          domain: "System Design",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Compiler Design",
              desc: "This is a card related to system design",
              author: "Varun Singla",
              imgurl: "cse_img/cd.jfif",
              playlistId: "PLxCzCOWd7aiEKtKSIHYusizkESC42diyc",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Operating System",
              desc: "This is a card related to system design",
              author: "Varun Singla",
              imgurl: "cse_img/os.jfif",
              playlistId: "PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Computer Networks",
              desc: "This is a card related to system design",
              author: "Varun Singla",
              imgurl: "cse_img/cn.jfif",
              playlistId: "PLxCzCOWd7aiGFBD2-2joCpWOLUrDLvVV_",
            },
            {
              cardId: "CSEC04",
              cardTitle: "Computer Sc - Systems Analysis and Design",
              desc: "This is a card related to system design",
              imgurl: "cse_img/csx11.jfif",
              author: "NPTEL",
              playlistId: "PL4F47209691234D1D",
            },
            {
              cardId: "CSEC05",
              cardTitle: "Digital System Design",
              desc: "This is a card related to system design",
              imgurl: "cse_img/csx14.jfif",
              author: "NPTEL IITM",
              playlistId: "PLyqSpQzTE6M_dZdF7Bd-UncI5_L_1VkXF",
            },
            {
              cardId: "CSEC06",
              cardTitle: "System Design Through VERILOG",
              desc: "This is a card related to system design",
              imgurl: "cse_img/csx13.png",
              author: "NPTEL IIT Guwahati",
              playlistId: "PLwdnzlV3ogoVGq4TIpX4NH6QEFYiAnyvA",
            },
          ],
        },
        {
          itemid: "CSEI07",
          noofcards: 6,
          domain: "Data Science",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Python for Data Science ",
              desc: "This is a card related to data science",
              author: "NPTEL IITM",
              imgurl: "cse_img/ds.jfif",
              playlistId: "PLyqSpQzTE6M_fFg1zZmeGIkenMDgXKGYi",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Data Science for Engineers",
              desc: "This is a card related to data science",
              author: "NPTEL IITM",
              imgurl: "cse_img/dse.jfif",
              playlistId: "PLyqSpQzTE6M-Rf2y3MT5aZ1UpTF1UQBK0",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Data Analytics with Python",
              desc: "This is a card related to data science",
              author: "Prof A. Ramesh",
              imgurl: "cse_img/csx8.jfif",
              playlistId: "PLLy_2iUCG87CNafffzNZPVa9rW-QmOmEv",
            },
            {
              cardId: "CSEC04",
              cardTitle: "Statistics for Data Science 1",
              desc: "This is a card related to data science",
              author: "NPTEL IITM",
              imgurl: "cse_img/csx9.jfif",
              playlistId: "PLZ2ps__7DhBYrMs3zybOqr1DzMFCX49xG",
            },
            {
              cardId: "CSEC05",
              cardTitle: "Introduction to Data Analytics",
              desc: "This is a card related to data science",
              author: "Prof. Balaraman Ravindran",
              imgurl: "cse_img/csx10.jfif",
              playlistId: "PLRueFtKLr0QN7MmQ8pdpQerOe_s8vGJG4",
            },
            {
              cardId: "CSEC06",
              cardTitle:
                "Essentials of Data Science With R Software - 1: Probability and Stastastical Interface",
              desc: "This is a card related to data science",
              author: "IIT Kharagpur",
              imgurl: "cse_img/csx12.jfif",
              playlistId: "PLFW6lRTa1g80s2MWqXNg2o0haq1k14v2I",
            },
          ],
        },
        {
          itemid: "CSEI08",
          noofcards: 6,
          domain: "Other Courses",
          cardlist: [
            {
              cardId: "CSEC01",
              cardTitle: "Computer Architecture and Organization",
              desc: "This is a card related to other courses",
              author: "Varun Singla",
              imgurl: "cse_img/coa.png",
              playlistId: "PLxCzCOWd7aiHMonh3G6QNKq53C6oNXGrX",
            },
            {
              cardId: "CSEC02",
              cardTitle: "Theory of Computation",
              desc: "This is a card related to other courses",
              author: "Varun Singla",
              imgurl: "cse_img/toc.jfif",
              playlistId: "PLxCzCOWd7aiFM9Lj5G9G_76adtyb4ef7i",
            },
            {
              cardId: "CSEC03",
              cardTitle: "Software Engineering",
              desc: "This is a card related to other courses",
              author: "Varun Singla",
              imgurl: "cse_img/se.jfif",
              playlistId: "PLxCzCOWd7aiEed7SKZBnC6ypFDWYLRvB2",
            },
            {
              cardId: "CSEC04",
              cardTitle: "Microprocessor Architecture",
              desc: "This is a card related to other courses",
              author: "Tutorials Point",
              imgurl: "cse_img/mpa.jfif",
              playlistId: "PLWPirh4EWFpFDi8bggPYOiMLlD1D_bBPM",
            },
            {
              cardId: "CSEC05",
              cardTitle: "Computer Graphics",
              desc: "This is a card related to other courses",
              author: "Deepak Garg",
              imgurl: "cse_img/cg.png",
              playlistId: "PLL8qj6F8dGlScni_9ZmeOMoRodrwzhvTq",
            },
            {
              cardId: "CSEC06",
              cardTitle: "Digital Logic And Design",
              desc: "This is a card related to other courses",
              author: "Varun Singla",
              imgurl: "cse_img/dld.jfif",
              playlistId: "PLxCzCOWd7aiGmXg4NoX6R31AsC5LeCPHe",
            },
          ],
        },
      ],
    },


    {
      id: "me01",
      courseName: "mechanical",
      items: [
        {
          itemid: "MEI01",
          noofcards: 6,
          domain: "Robotics",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "Robotics",
              desc: "This is a card related to robotics",
              author: "Prof. D K Pratihar",
              imgurl: "me_img/r6.jfif",
              playlistId: "PLbRMhDVUMngcdUbBySzyzcPiFTYWr4rV_",
            },
            {
              cardId: "MEC02",
              cardTitle: "Introduction to Robotics",
              desc: "This is a card related to robotics",
              author: "NPTEL IITM",
              imgurl: "me_img/r5.jfif",
              playlistId: "PLyqSpQzTE6M_XM9cvjLLO_Azt1FkgPhpH",
            },
            {
              cardId: "MEC03",
              cardTitle: "Robotics and Control: Theory and Practice",
              desc: "This is a card related to robotics",
              author: "IIT ROORKEE",
              imgurl: "me_img/r4.jfif",
              playlistId: "PLLy_2iUCG87AjAXKbNMiKJZ2T9vvGpMB0",
            },
            {
              cardId: "MEC04",
              cardTitle: "Mechanics and Control of Robotic Manipulators",
              desc: "This is a card related to robotics",
              author: "NPTEL IITM",
              imgurl: "me_img/r3.jfif",
              playlistId: "PLyqSpQzTE6M-tWPjnJjFo9sHGWxgCnGrh",
            },
            {
              cardId: "MEC05",
              cardTitle: "Robotics: Basics and Selected Advanced Concepts",
              desc: "This is a card related to robotics",
              author: "IISC Banglore",
              imgurl: "me_img/r2.jfif",
              playlistId: "PLgMDNELGJ1CZT9pdEEkDylXFPLdcqxn0t",
            },
            {
              cardId: "MEC06",
              cardTitle: "Industrial Robotics and Automation Course",
              desc: "This is a card related to robotics",
              author: "Arun Dayal Udai",
              imgurl: "me_img/r1.jfif",
              playlistId: "PLXDsvE7qtfNdt9oYEhJ_LMXDUGu6bH-L6",
            },
          ],
        },
        {
          itemid: "MEI02",
          noofcards: 7,
          domain: "Thermodynamics",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "Introduction to Thermodynamics",
              desc: "This is a card related to thermodynamics",
              author: "NPTEL IITM",
              imgurl: "me_img/th1.jfif",
              playlistId: "PLyqSpQzTE6M_QOKxVxZ5nQ48gOkzg7zWP",
            },
            {
              cardId: "MEC02",
              cardTitle: "MATLAB Programming for Numerical Computation NPTEL",
              desc: "This is a card related to thermodynamics",
              author: "Prof. Niket",
              imgurl: "me_img/th2.jfif",
              playlistId: "PLRWKj4sFG7-6_Xr9yqg6SMr_F80KdFVhN",
            },
            {
              cardId: "MEC03",
              cardTitle: "Thermodynamics: classical to statistical",
              desc: "This is a card related to thermodynamics",
              author: "NPTEL IIT Guwahati",
              imgurl: "me_img/th3.jfif",
              playlistId: "PLwdnzlV3ogoX-WIPb5DnmmmUOVAgI5wrq",
            },
            {
              cardId: "MEC04",
              cardTitle: "Advanced Thermodynamics and Combustion",
              desc: "This is a card related to thermodynamics",
              author: "Prof. Niranjan Sahoo",
              imgurl: "me_img/th4.jfif",
              playlistId: "PLwdnzlV3ogoUcPrKLKz1_j0s89VzvZfnx",
            },
            {
              cardId: "MEC05",
              cardTitle: "Chemical Engineering Thermodynamics",
              desc: "This is a card related to thermodynamics",
              author: "Prof. Shashidhar Gumma",
              imgurl: "me_img/th5.jfif",
              playlistId: "PLwdnzlV3ogoVnCnIfjDHng_8biZSUEYtK",
            },
            {
              cardId: "MEC06",
              cardTitle: "Thermodynamics - GATE",
              desc: "This is a card related to thermodynamics",
              author: "GATE Academy Plus",
              imgurl: "me_img/th6.jfif",
              playlistId: "PL9RcWoqXmzaK6AHCCyL_J6gqc02RN-w-D",
            },
            {
              cardId: "MEC07",
              cardTitle: "Engineering Thermodynamics",
              desc: "This is a card related to thermodynamics",
              author: "EveryEng - Mechanical",
              imgurl: "me_img/th7.png",
              playlistId: "PLDDfbf7FIeqsPqMnCiU6dvkb6TbG21ucz",
            },
          ],
        },
        {
          itemid: "MEI03",
          noofcards: 4,
          domain: "Propulsion",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "IC Engines and Gas Turbines",
              desc: "This is a card related to propulsion",
              author: "NPTEL IITM",
              imgurl: "me_img/pp1.jfif",
              playlistId: "PLwdnzlV3ogoXHbVNKWL1BYOo_8PpyNtnC",
            },
            {
              cardId: "MEC02",
              cardTitle: "Fundamentals of Automotive Systems",
              desc: "This is a card related to propulsion",
              author: "NPTEL IITM",
              imgurl: "me_img/pp2.jfif",
              playlistId: "PLyqSpQzTE6M9G2SNxKfsVEjcM9MlJau4F",
            },
            {
              cardId: "MEC03",
              cardTitle: "Aircraft Propulsion",
              desc: "This is a card related to propulsion",
              author: "Prof. Vinayak Kulkarni",
              imgurl: "me_img/pp3.jfif",
              playlistId: "PLwdnzlV3ogoWEYkr5o3OD4cv5v7ba10Lm",
            },
            {
              cardId: "MEC04",
              cardTitle: "Introduction to Rocket Propulsion",
              desc: "This is a card related to propulsion",
              author: "Prof. Dr D.P. Mishra",
              imgurl: "me_img/pp4.jfif",
              playlistId: "PLFW6lRTa1g82gOQCc1aR4r7uyCbdmpL0D",
            },
          ],
        },
        {
          itemid: "MEI04",
          noofcards: 6,
          domain: "Mechanics",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "Engineering Mechanics",
              desc: "This is a card related to mechanics",
              author: "NPTEL IITM",
              imgurl: "me_img/m2.jfif",
              playlistId: "PLyqSpQzTE6M_MEUdn1izTMB2yZgP1NLfs",
            },
            {
              cardId: "MEC02",
              cardTitle: "Theoretical Mechanics",
              desc: "This is a card related to mechanics",
              author: "NPTEL IIT Guwahati",
              imgurl: "me_img/m3.jfif",
              playlistId: "PLwdnzlV3ogoXUbQmP-T2gPhYXeEcxP6U8",
            },
            {
              cardId: "MEC03",
              cardTitle: "Classical Mechanics",
              desc: "This is a card related to mechanics",
              author: "IIT Kharagpur",
              imgurl: "me_img/m4.jfif",
              playlistId: "PLdOM9VfSZfHNPDJCUthjWHBeAgyn3IuzM",
            },
            {
              cardId: "MEC04",
              cardTitle: "",
              desc: "This is a card related to mechanics",
              author: "",
              imgurl: "me_img/m5.png",
              playlistId: "",
            },
            {
              cardId: "MEC05",
              cardTitle: "Introduction to Classical Mechanics",
              desc: "This is a card related to mechanics",
              author: "NPTEL IITM",
              imgurl: "me_img/m6.jfif",
              playlistId: "PLyqSpQzTE6M_d9f-9fKxUQYR1qI5YEnSz",
            },
            {
              cardId: "MEC06",
              cardTitle: "Engineering Mechanics ",
              desc: "This is a card related to mechanics",
              author: "Unacademy",
              imgurl: "me_img/m7.jfif",
              playlistId: "PLiSPNzs4fD9tyI_gNHcQkvtvzLvB3aE05",
            },
          ],
        },
        {
          itemid: "MEI05",
          noofcards: 6,
          domain: "Dynamics and Vibration",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "Mechanical Vibration",
              desc: "This is a card related to dynamics and vinration",
              author: "Unacademy",
              imgurl: "me_img/dv3.jfif",
              playlistId: "PLiSPNzs4fD9spvBAr_fpt5SIe-Eg1YoN9",
            },
            {
              cardId: "MEC02",
              cardTitle: "Vibration and Structural Dynamics",
              desc: "This is a card related to dynamics and vinration",
              author: "Prof. Mira Mitra",
              imgurl: "me_img/dv4.jfif",
              playlistId: "PLbRMhDVUMngdM3vvYapHCEPTiEvoATCHS",
            },
            {
              cardId: "MEC03",
              cardTitle: "Introduction to Mechanical Vibration",
              desc: "This is a card related to dynamics and vinration",
              author: "Dr. Anil Kumar",
              imgurl: "me_img/dv5.jfif",
              playlistId: "PLSGws_74K01_pG3R7rgtDtrDZBjcTgPdR",
            },
            {
              cardId: "MEC04",
              cardTitle: "Dynamics of Machinery",
              desc: "This is a card related to dynamics and vinration",
              author: "Mechanical & Automobile",
              imgurl: "me_img/dv6.jfif",
              playlistId: "PLQmc-I2-FO2HKvASHKTX3_T6s0PD6DtWj",
            },
            {
              cardId: "MEC05",
              cardTitle: "DOM(Vibration)",
              desc: "This is a card related to dynamics and vinration",
              author: "Education Lessons",
              imgurl: "me_img/dv1.jfif",
              playlistId: "PLwpA_XrwdvgYT6cqLRYVOgy8hS1h0UnmI",
            },
            {
              cardId: "MEC06",
              cardTitle: "Vibration",
              desc: "This is a card related to dynamics and vinration",
              author: "Unacademy",
              imgurl: "me_img/dv2.jfif",
              playlistId: "PLiSPNzs4fD9s0sCnTRd6M6gX86BHCCJOH",
            },
          ],
        },
        {
          itemid: "MEI06",
          noofcards: 11,
          domain: "University Courses",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle: "Alternative Energy Sources",
              desc: "This is a card related to university courses",
              author: "Dr. Jignesh Mehta",
              imgurl: "me_img/mx1.webp",
              playlistId: "PL7SouPSb4ISJHZ_KfmaTESpIkWs3ydpPm",
            },
            {
              cardId: "MEC02",
              cardTitle: "Refrigeration and Air Conditioning",
              desc: "This is a card related to university courses",
              author: "Dr. Jignesh Mehta",
              imgurl: "me_img/mx2.webp",
              playlistId: "PL7SouPSb4ISJ25wXZny4Dz9O-fiaOcJnX",
            },
            {
              cardId: "MEC03",
              cardTitle:
                "Differential Calculus For B.Sc. and Engineering Students",
              desc: "This is a card related to university courses",
              author: "Dr. Gajendra Purohit",
              imgurl: "me_img/mx4.png",
              playlistId: "PL7SouPSb4ISJChVYEUyN2-ZHSeHNbPfXF",
            },
            {
              cardId: "MEC04",
              cardTitle: "Energy and solar cooking",
              desc: "This is a card related to university courses",
              author: "Dr. Jignesh Mehta",
              imgurl: "me_img/mx3.webp",
              playlistId: "PL7SouPSb4ISJChVYEUyN2-ZHSeHNbPfXF",
            },
            {
              cardId: "MEC05",
              cardTitle: "Differential Equation",
              desc: "This is a card related to university courses",
              author: "Dr. Gajendra Purohit",
              imgurl: "me_img/mx5.png",
              playlistId: "PLU6SqdYcYsfJmqo86d12EoNNWKtAZqu8q",
            },
            {
              cardId: "MEC06",
              cardTitle: "Introduction to Materials Science and Engineering",
              desc: "This is a card related to university courses",
              author: "Prof Rajesh Prasad",
              imgurl: "me_img/mx6.jfif",
              playlistId: "PLyAZSyX8Qy5Am_2StOOQ5vCUE3VIcAenE",
            },
            {
              cardId: "MEC07",
              cardTitle: "Vector Calculus",
              desc: "This is a card related to university courses",
              author: "Dr. Gajendra Purohit",
              imgurl: "me_img/mx7.webp",
              playlistId: "PLU6SqdYcYsfJz9FAzbgocIjlkw4NXAar-",
            },
            {
              cardId: "MEC08",
              cardTitle: "Laplace Transform ",
              desc: "This is a card related to university courses",
              author: "Dr. Gajendra Purohit",
              imgurl: "me_img/mx8.webp",
              playlistId: "PLU6SqdYcYsfILCRFpIM3fQdVIzOo71snJ",
            },
            {
              cardId: "MEC09",
              cardTitle: "MATRICES (ENGINEERING MATHS SEM-1)",
              desc: "This is a card related to university courses",
              author: "Saurabh Dahivadkar",
              imgurl: "me_img/mx9.jfif",
              playlistId: "PLKS7ZMKnbPrT-Gy4k0r8jAr0mX2K32yyV",
            },
            {
              cardId: "MEC010",
              cardTitle: "ENGINEERING MECHANICS",
              desc: "This is a card related to university courses",
              author: "Tikle's Academy",
              imgurl: "me_img/mx10.jfif",
              playlistId: "PLDN15nk5uLiAyM7MbRBF1eIFC8y5vMRxI",
            },
            {
              cardId: "MEC011",
              cardTitle: "A.C. CIRCUITS | A.C. FUNDAMENTALS",
              desc: "This is a card related to university courses",
              author: "Tikle's Academy",
              imgurl: "me_img/mx11.png",
              playlistId: "PLDN15nk5uLiCD8HljuyVX86WVeqTCml33",
            },
          ],
        },
        {
          itemid: "MEI07",
          noofcards: 7,
          domain: "University Courses",
          cardlist: [
            {
              cardId: "MEC01",
              cardTitle:
                "Dynamic of machine (DOM) lecture for universities exams",
              desc: "This is a card related to university courses",
              author: "Edu Grown",
              imgurl: "me_img/mx12.webp",
              playlistId: "PLelAq9xzEDXCpJbs5K6kN9LyA9TDHiLed",
            },
            {
              cardId: "MEC02",
              cardTitle: "AutoCAD 2D Full Tutorial",
              desc: "This is a card related to university courses",
              author: "Deepak Verma",
              imgurl: "me_img/mx13.png",
              playlistId: "PLMtzJAOD3B7Z0kAGbqdVPZuT91pNIsF-R",
            },
            {
              cardId: "MEC03",
              cardTitle: "PROJECTION OF SOLIDS",
              desc: "This is a card related to university courses",
              author: "Tikle's Academy",
              imgurl: "me_img/mx14.png",
              playlistId: "PLDN15nk5uLiA9qy-OWuoEYoXsu7lsSaE9",
            },
            {
              cardId: "MEC04",
              cardTitle: "Basic Thermodynamics",
              desc: "This is a card related to university courses",
              author: "Unacademy",
              imgurl: "me_img/mx15.png",
              playlistId: "PLiSPNzs4fD9snxh0jHSuk3HuqoMhW24VO",
            },
            {
              cardId: "MEC05",
              cardTitle: "Integral Calculus",
              desc: "This is a card related to university courses",
              author: "Dr. Gajendra Purohit",
              imgurl: "me_img/mx16.jfif",
              playlistId: "PLU6SqdYcYsfLoKyzF_dwxAQf8lIi6VC54",
            },
            {
              cardId: "MEC06",
              cardTitle: "Thermal Engineering",
              desc: "This is a card related to university courses",
              author: "Polytechnic Pathshala",
              imgurl: "me_img/mx17.webp",
              playlistId: "PLsSgFix02l7sR67kN65fFcZGSv-g5OIvE",
            },
            {
              cardId: "MEC07",
              cardTitle: "Governor | Governors (Theory of machines) all lectures",
              desc: "This is a card related to university courses",
              author: "Mechanical Engineering",
              imgurl: "me_img/mx18.webp",
              playlistId: "PLYRGB44zNZWX45eXHZmMEuR7wkuhSlMKz",
            },
          ],
        },
      ],
    },

    {
      id: "che01",
      courseName: "chemical",
      items: [
        {
          itemid: "CI01",
          noofcards: 5,
          domain: " Engineering Thermodynamics",
          cardlist: [
            {
              cardId: "C01",
              cardTitle: "Chemical Engineering Thermodynamics",
              desc: "This is a card related to engineering thermodynamics",
              author: "Prof. Shashidhar Gumma",
              imgurl: "c_img/c2.jfif",
              playlistId: "PLwdnzlV3ogoVnCnIfjDHng_8biZSUEYtK",
            },
            {
              cardId: "C02",
              cardTitle: "Mass Transfer 1",
              desc: "This course will provide an overview of mass transfer operation at basic to an intermediate level. Coverage will be relatively broad. This course applies the concepts of diffusion and interphase mass transfer to the analysis of different mass transfer operations such as absorption and distillation. The goal is to provide students with the theoretical/analytical background to understand mass transfer operations as well as application and to tackle the sort of complex problems.",
              author: "Prof. Bishnupada Mandal",
              imgurl: "c_img/c3.wepp",
              playlistId: "PLwdnzlV3ogoVX_S_8DyKa7RudEazDL0o_",
            },
            {
              cardId: "C03",
              cardTitle: "Chemical reaction engineering - I",
              desc: "This course will provide an overview of chemical kinetics and reactor design at basic to an intermediate level. Coverage will be relatively broad. This course applies the concepts of reaction rate, stoichiometry and equilibrium to the analysis of chemical and biological reacting systems such as derivation of rate expressions from reaction mechanisms and equilibrium or steady state assumptions and design of chemical and biochemical reactors via synthesis of chemical kinetics, and mass and energy balances. The goal is to provide students with the theoretical/analytical background to understand chemical kinetics and reactor design and to tackle the short of complex problems.",
              author: "Prof. Bishnupada Mandal",
              imgurl: "c_img/c4.webp",
              playlistId: "PLwdnzlV3ogoUC9IWVOPTGqV5eEVNRAfGa",
            },
            {
              cardId: "C04",
              cardTitle: "Chemical Engineering Thermodynamics",
              desc: "This course covers the foundation of classical thermodynamics in the form of postulates, and later their applications to open and close systems, criteria of stability and equilibria, the equation of states, properties of pure fluids and mixtures, theories and model of phase equilibrium, and chemical reaction equilibrium. The major focus in the first half of the course would be to build a strong foundation in the subject. The second part of the course will emphasis the application of the thermodynamics on chemical engineering problems related to phase equilibria.",
              author: "Prof. Jayant Singh",
              imgurl: "c_img/c1.jfif",
              playlistId: "PLFW6lRTa1g80QsuYcFQZWrsn_PB987gn5",
            },
            {
              cardId: "C05",
              cardTitle: "Phase Equilibrium Thermodynamics",
              desc: "",
              author: "Prof. Gargi Das",
              imgurl: "c_img/c5.jfif",
              playlistId: "PLUYS69edf4tgJf8sV3BvtOfojXzL1yMKD",
            },
          ],
        },
        {
          itemid: "CI02",
          noofcards: 6,
          domain: "Computational Chemical Engineering",
          cardlist: [
            {
              cardId: "C01",
              cardTitle: "Chemical - Computational Techniques",
              desc: "This is a card related to Computational Chemical Engineering",
              author: "Prof. Niket Kaisare",
              imgurl: "c_img/c6.jfif",
              playlistId: "PL42204FB1209D0EC3",
            },
            {
              cardId: "C02",
              cardTitle:
                "Basic Principles and Calculations in Chemical Engineering",
              desc: "This is a card related to Computational Chemical Engineering",
              author: "NPTEL IIT Guwahati",
              imgurl: "c_img/c7.jfif",
              playlistId: "PLwdnzlV3ogoXpDif2e93GJKoojj0SgvV0",
            },
            {
              cardId: "C03",
              cardTitle:
                "Computational Chemistry and Classical Molecular Dynamics",
              desc: "This is a card related to Computational Chemical Engineering",
              author: "Prof B.L.Tembe",
              imgurl: "c_img/c8.jfif",
              playlistId: "PLOzRYVm0a65fCJJQendwEEcSrC8iwvgBn",
            },
            {
              cardId: "C04",
              cardTitle: "MATLAB Programming for Numerical Computation ",
              desc: "This is a card related to Computational Chemical Engineering",
              author: "Prof. Niket Kaisare",
              imgurl: "c_img/matlab.png",
              playlistId: "PLRWKj4sFG7-6_Xr9yqg6SMr_F80KdFVhN",
            },
            {
              cardId: "C05",
              cardTitle: "Foundation of Computational Fluid Dynamics",
              desc: "This is a card related to Computational Chemical Engineering",
              author: "Prof Vengadesan",
              imgurl: "c_img/c9.jfif",
              playlistId: "PLaDq_DX7U7V91gf-LrGdx0Yg68KW1Xljq",
            },
            {
              cardId: "C06",
              cardTitle: "Material and Energy Balances",
              desc: "This is a card related to Computational Chemical Engineering",
              author: "NPTEL IITM",
              imgurl: "c_img/c10.jfif",
              playlistId: "PLyqSpQzTE6M-QFqMp7_FJ_NuGCXDuHqvf",
            },
          ],
        },
        {
          itemid: "CI03",
          noofcards: 6,
          domain: "Energy and Environment",
          cardlist: [
            {
              cardId: "C01",
              cardTitle: "Environmental Quality Monitoring & Analysis",
              desc: "This card is related to energy and envionment",
              author: "NPTEL IITM",
              imgurl: "c_img/c11.jfif",
              playlistId: "PLyqSpQzTE6M_2XsRlRiBKZ6chp1a9H8eI",
            },
            {
              cardId: "C02",
              cardTitle: "Non-Conventional Energy Resources",
              desc: "This card is related to energy and envionment",
              author: "NPTEL",
              imgurl: "c_img/c12.jfif",
              playlistId: "PL3QMEfkolRFbGhXveCE7RFDBgY0_gRxkh",
            },
            {
              cardId: "C03",
              cardTitle: "Solar Energy Engineering and Technology",
              desc: "This card is related to energy and envionment",
              author: "NPTEL IIT Guwahati",
              imgurl: "c_img/c13.jfif",
              playlistId: "PLwdnzlV3ogoUtaGiq-lVJc4CC6x_czs9D",
            },
            {
              cardId: "C04",
              cardTitle:
                "Renewable Energy Engineering: Solar, Wind and Biomass Energy System",
              desc: "This card is related to energy and envionment",
              author: "NPTEL IIT Guwahati",
              imgurl: "c_img/c18.jfif",
              playlistId: "PLwdnzlV3ogoXUifhvYB65lLJCZ74o_fAk",
            },
            {
              cardId: "C05",
              cardTitle:
                "Basic Environmental Engineering and Pollution Abatement",
              desc: "This card is related to energy and envionment",
              author: "IIT ROORKEE",
              imgurl: "c_img/c14.jfif",
              playlistId: "PLLy_2iUCG87Cr__rs9sS1zSaR62imd0uB",
            },
            {
              cardId: "C06",
              cardTitle: "Biomass Conversion and Biorefinery",
              desc: "This card is related to energy and envionment",
              author: "NPTEL IIT Guwahati",
              imgurl: "c_img/c15.jfif",
              playlistId: "PLwdnzlV3ogoW6JKdbQWirzk3k9MeUQZFH",
            },
          ],
        },
        {
          itemid: "CI03",
          noofcards: 4,
          domain: "Oil and Gas Industry",
          cardlist: [
            {
              cardId: "C01",
              cardTitle:
                "Petroleum Refining - Complete Guide to Products & Processes",
              desc: "This card is related to oil and gas industry",
              author: "Chemical Engneering Guy",
              imgurl: "c_img/c19.webp",
              playlistId: "PLXGHfCedMmsO0dIXuOgD7vwO-ISzGHJRx",
            },
            {
              cardId: "C02",
              cardTitle: "Petrochemicals - An Overview Course",
              desc: "This card is related to oil and gas industry",
              author: "Chemical Engneering Guy",
              imgurl: "c_img/c20.jfif",
              playlistId: "PLXGHfCedMmsMK-9KgLgmpxCsnDvWYx6jO",
            },
            {
              cardId: "C03",
              cardTitle: "Unit Operations in Chemical Engineering",
              desc: "This card is related to oil and gas industry",
              author: "Chemical Engneering Guy",
              imgurl: "c_img/c16.jfif",
              playlistId: "PLXGHfCedMmsN8ty5RDEXNC9Ndr6puC2hJ",
            },
            {
              cardId: "C04",
              cardTitle: "Gas Absorption & Stripping",
              desc: "This card is related to oil and gas industry",
              author: "Chemical Engneering Guy",
              imgurl: "c_img/c17.jfif",
              playlistId: "PLXGHfCedMmsN-mgj9OaWBScLJgypUsxlw",
            },
          ],
        },
        {
          itemid: "CI04",
          noofcards: 6,
          domain: "University Courses",
          cardlist: [
            {
              cardId: "C01",
              cardTitle: "Mass Balance",
              desc: "This course is related to university courses",
              author: "Chemical Engneering Guy",
              imgurl: "c_img/c21.png",
              playlistId: "PLXGHfCedMmsO_kDonG2lY86irrHtJ0ItF",
            },
            {
              cardId: "C02",
              cardTitle: "Reactor Engineering",
              desc: "This course is related to university courses",
              author: "Chemical Engneering Guy",
              imgurl: "c_img/c22.jfif",
              playlistId: "PLXGHfCedMmsP-pKqop8a1JSvc_2e9hCGe",
            },
            {
              cardId: "C03",
              cardTitle: "Thermodynamics",
              desc: "This course is related to university courses",
              author: "Chemical Engneering Guy",
              imgurl: "c_img/c23.webp",
              playlistId: "PLXGHfCedMmsNbBreVywSRPyc25IRo4R8q",
            },
            {
              cardId: "C04",
              cardTitle: "Aspen Plus",
              desc: "This course is related to university courses",
              author: "Chemical Engneering Guy",
              imgurl: "c_img/c23.png",
              playlistId: "PLXGHfCedMmsNbBreVywSRPyc25IRo4R8q",
            },
            {
              cardId: "C05",
              cardTitle: "Aspen Plus Physical Properties",
              desc: "This course is related to university courses",
              author: "Chemical Engneering Guy",
              imgurl: "c_img/c24.webp",
              playlistId: "PLXGHfCedMmsPQGjZdMsnnQqnXAWqkoxrI",
            },
            {
              cardId: "C06",
              cardTitle: "Applied Fluid Dynamics (PART 1: Incompressible Flow)",
              desc: "This course is related to university courses",
              author: "Chemical Engneering Guy",
              imgurl: "c_img/c25.webp",
              playlistId: "PLXGHfCedMmsM1KK5dAmYVCMtiK93ipxsR",
            },
          ],
        },
      ],
    },


  ];
module.exports = courses;